INSERT INTO USUARIOS (NOMBRE, APELLIDO , EMAIL, PASS) VALUES('Jose', 'Peregrina', 'email@example.com', 'password');

INSERT INTO LICENCIA(EMPRESA ,OFFICE, DEPARTAMENTO, CIUDAD, COMENTARIOS) VALUES('LA MADRILEÑA', TRUE, 'Administración', 'CDMX', 'Justo lo que necesitabamos');
INSERT INTO LICENCIA(EMPRESA ,OFFICE, DEPARTAMENTO, CIUDAD, COMENTARIOS) VALUES('Don Celular', TRUE, 'CONTABILIDAD 2', 'Guadalajara', 'ESTA MUY CARO');
INSERT INTO LICENCIA(EMPRESA ,OFFICE, DEPARTAMENTO, CIUDAD, COMENTARIOS) VALUES('Banco Riendo', TRUE, 'Contabilidad', 'CDMX', 'Podrían mejorar el servicio');
INSERT INTO LICENCIA(EMPRESA ,OFFICE, DEPARTAMENTO, CIUDAD, COMENTARIOS) VALUES('LA MADRILEÑA', TRUE, 'Publicidad', 'Zacatecas', 'Que cool, muchas gracias');

INSERT INTO CELULAR(EMPRESA, CIUDAD, DEPARTAMENTO, PUESTO, TIPO) VALUES('LA MADRILEÑA', 'CDMX', 'TALLER DE REPARACIONES', 'JEFE DE AREA', 'SENCILLO');
INSERT INTO CELULAR(EMPRESA, CIUDAD, DEPARTAMENTO, PUESTO, TIPO) VALUES('LA PACA', 'QUERETARO', 'TALLER DE TEXTILES', 'SEGURIDAD', 'SMARTPHONE');

INSERT INTO COMPUTO(EMPRESA, CIUDAD, DEPARTAMENTO, PUESTO, TIPO) VALUES('LA MADRILEÑA', 'COLIMA', 'CONTABILIDAD', 'CONTADOR', 'ESCRITORIO');
INSERT INTO COMPUTO(EMPRESA, CIUDAD, DEPARTAMENTO, PUESTO, TIPO) VALUES('Banco Riendo', 'COLIMA', 'PUBLICIDAD', 'RELACIONES PUVLICAS', 'LAPTOP');
