CREATE TABLE USUARIO(
    USUARIO_ID bigint auto_increment PRIMARY KEY,
    NOMBRE VARCHAR(16) NOT NULL,
    APELLIDO VARCHAR(16) NOT NULL,
    EMAIL VARCHAR(32) NOT NULL,
    PASS VARCHAR(16) NOT NULL
);

CREATE TABLE LICENCIA(
    LICENCIA_ID bigint auto_increment PRIMARY KEY,
    EMPRESA VARCHAR(32) NOT NULL,
    OFFICE BOOLEAN NOT NULL,
    DEPARTAMENTO VARCHAR(32) NOT NULL,
    CIUDAD VARCHAR(32) NOT NULL,
    COMENTARIOS VARCHAR(255)
)

CREATE TABLE CELULAR(
    CELULAR_ID bigint auto_increment PRIMARY KEY,
    EMPRESA VARCHAR(32) NOT NULL,
    CIUDAD VARCHAR(32) NOT NULL,
    DEPARTAMENTO VARCHAR(32) NOT NULL,
    PUESTO VARCHAR(32) NOT NULL,
    TIPO VARCHAR(16) NOT NULL
)

CREATE TABLE COMPUTO(
    COMPUTO_ID bigint auto_increment PRIMARY KEY,
    EMPRESA VARCHAR(32) NOT NULL,
    CIUDAD VARCHAR(32) NOT NULL,
    DEPARTAMENTO VARCHAR(32) NOT NULL,
    PUESTO VARCHAR(32) NOT NULL,
    TIPO VARCHAR(16)
)
